version: '3'

services:
  tg-bot:
    container_name: flibusta-tg-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./books:/srv/books
      - ./logs:/srv/logs
      - ./data:/srv/data
      # Раскомментируйте для hot-reload при разработке:
      # - ./src:/srv/src
